### ISSUE TITLE
[BUG] Volume adjustments at 1/4 increments do not work while Beardie is running

### ISSUE THREAD

**Issue by fabeschan** [Stillness-2/beardie#14]
I use option+shift+vol up/down a lot to fine-tune the sound volume, but it doesn't work as soon as Beardie is launched. Pressing those keys will change the volume in full increments instead of 1/4 fractions.

If I close/quit Beardie then the problem immediately goes away.

I also tried removing all keyboard shortcuts on the Beardie preferences pane but that results in no behavior change.

**Comment by Stillness-2** [comment]
I didn't know at all that there is such a way to change the volume :)
