### ISSUE TITLE
[Request] Swinsian support

### ISSUE THREAD

**Issue by doersino** [Stillness-2/beardie#16]
As a user of BeardedSpice, I'm glad that you've taken up the baton and are continuing to develop this tool!

[Swinsian](https://swinsian.com) support is a feature that's been [requested of BeardedSpice at least five times](https://github.com/beardedspice/beardedspice/issues?q=is%3Aissue+is%3Aopen+swinsian), someone's even taken the time to [compile a list of the required AppleScript commands](https://github.com/beardedspice/beardedspice/issues/490#issuecomment-265353250). Here's also a [link to its scripting reference](https://swinsian.com/support/scripting/). All this makes me hopeful that adding support for it wouldn't be too difficult.

Swinsian is a lightweight replacement for iTunes (or, now, the MP3-playing portion of Music.app) that I, personally, find to be a joy to use – hence this request. Downloading a fully-featured trial version of it should allow you to verify whether things work properly.

I'd be really grateful if you took the time to implement this!

**Comment by doersino** [comment]
Wow, that was quick – thank you so much, this is great!

When's the next release scheduled, if I may ask?

**Comment by Stillness-2** [comment]
@doersino a week or two later, if will no issues
