### ISSUE TITLE
Beardie-nm-connector taking a lot of CPU resource.

### ISSUE THREAD

**Issue by andychongyz** [Stillness-2/beardie#26]
Hi, can I know why it is taking so many CPU resources? My Macbook fan is on 🔥  hahaha

![image](https://user-images.githubusercontent.com/12697240/139769901-a5d012d2-0c77-46bf-9ce9-578d9057a09c.png)

**Comment by Stillness-2** [comment]
@andychongyz Can you sample in Activity Monitor when a process is using a lot of CPU?

**Comment by panosru** [comment]
@Stillness-2 I'm facing the same issue:
![image](https://user-images.githubusercontent.com/400362/160299137-ba829085-aa23-4666-8a63-1132a705ba94.png)

Sample can be found [here](https://controlc.com/f6df046b).
