### ISSUE TITLE
[Request] App Priority Control

### ISSUE THREAD

**Issue by panosru** [Stillness-2/beardie#3]
Hi! I saw your post [here](https://github.com/beardedspice/beardedspice/issues/899#issuecomment-547650003), and really appreciate the effort!

Is it possible to place Apple Music after iTunes or even provide the ability to rearrange the priority?

thanks!

UPDATE:
I'm not sure actually if the order of the apps in the list implies the priority, for example, if you have Apple Music running and if the app is above Spotify in the list then it should be controlled, and so on.

**Comment by Stillness-2** [comment]
@panosru Have you tried the latest alpha? 
Beardie automatically chooses which player to control. The user does not need to prioritize. You can keep several players running, the "desired one" will be controlled. :) Such magic... :)

Also, if you are not satisfied with the current player, you can switch between running players using hotkeys

**Comment by panosru** [comment]
@Stillness-2 yeap! I downloaded at the time I wrote the _"issue"_ :D 

I see what you mean by magic, it is cool, it actually tracks the last active player and keeps routes the media keys to it, meaning that if I have a YouTube tab open in Edge, Apple Music open and Spotify as well, then the media keys will be talking to the last player with which you interacted.

That is cool, if I may a couple of things that I would also love to have:

1. I have set Spotify to launch on startup, but if after a boot I just hit the play button, Apple Music is launched, I would like for the app to be able to detect that a) a media app is already running, b) if more than one media apps are running then handle the one with higher priority (order) in the list.
2. Be able to disable the magic and just have a priority-based system that would always handle the running application with the highest priority, if none is running then will launch the application with the highest priority.

Again, thanks a lot for the project!

**Comment by Stillness-2** [comment]
@panosru 
1. This is a bug, and it seems I fixed it in the latest build. If the Beadie app is running, the Music app should not launch when you press play button.
2. You propose a completely different concept of the application. I am not ready to change the current concept, as it suits me completely. As a customization of the behavior, you can try disabling adapters/strategies in the application settings. :)
