### ISSUE TITLE
Version 3.0.19 - Can't detect Chrome's Youtube

### ISSUE THREAD

**Issue by Zeit42** [Stillness-2/beardie#30]
It started yesterday, Beardie did not seem to detect the youtube tabs in Google Chrome. I tried restarting Chrome, restarting Beardie, shutting down Spotify for a while, but nothing worked.

**Comment by Zeit42** [comment]
Not sure if this is a bug on the latest version but since yesterday, Beardie doesn't seem to detect Google Chrome's Youtube Tab at all. I tried restarting my browser, restarting Beardie, and even closing Spotify but nothing worked.

**Comment by AlexandruGG** [comment]
I am seeing this as well, at first I thought it was an issue with using it on an M1 Mac. But looks like version 3.0.17 works fine
