### ISSUE TITLE
Media keys work for a while then stop

### ISSUE THREAD

**Issue by borg** [Stillness-2/beardie#32]
Yep
It's sad. 
Upgraded to Big Sur. Lost control of Spotify again. Installed Beardie. 
Media keys work for a while, then stop. Wish I had more debug info. 
Probably Apple being Nazis.

**Comment by Stillness-2** [comment]
This is strange ... In theory, this can happen if the Beardie hangs. Does this happen after waking up from sleep, or changing the network environment?

**Comment by borg** [comment]
In the last couple of days it has been playing nicely actually. Yay.
It's possible it happens after VPN/network changes. Will report back if I can pin point next time it happens.

**Comment by swrobel** [comment]
I use the Spotify Mac app, and this has been happening to me frequently lately. Beardie isn't frozen, and I can interact with the menubar icon, but it says something like "no open tabs" at the top of the menu that opens when I click the menubar icon. Quitting beardie and restarting it gets it working again, and at the present moment it says "Spotify | {track info}" in the menu, and media buttons control Spotify as expected.

**Comment by Stillness-2** [comment]
Test this build
[Beardie.app.zip](https://github.com/Stillness-2/beardie/files/9438225/Beardie.app.zip)

may be ...

@swrobel @borg

**Comment by swrobel** [comment]
@Stillness-2 hmmm, why?
<img width="258" alt="Screen Shot 2022-08-30 at 9 38 58 AM" src="https://user-images.githubusercontent.com/157270/187492437-3bf590c2-91f9-48e0-9dc3-715355517f51.png">

**Comment by Stillness-2** [comment]
Strange, I didn't have this request
