### ISSUE TITLE
Bug: beardie-nm-connector process using lots of power

### ISSUE THREAD

**Issue by bentoon00** [Stillness-2/beardie#44]
[ Similar to #26 ]
After checking activity monitor, the beardie-nm-connector process is using far more power in the background than any other open and active process, even Spotify when actively playing music. The process doesn't appear in the battery menu tab as high usage, only Google Chrome. Perhaps this has something to do with the installed Chrome + Beardie extension?
The process's CPU and power usage stays the same when Spotify is playing, paused and closed (completely).

Process sample attatched below
Device: M1 Max MacBook Pro 16" - Battery health 99%
OS: Ventura 13.2.1 

<img width="1246" alt="Screenshot 2023-03-26 at 15 54 58" src="https://user-images.githubusercontent.com/124264994/227784168-da7053ff-e004-43c4-b469-d68505bdb2f8.png">
<img width="510" alt="Screenshot 2023-03-26 at 15 57 04" src="https://user-images.githubusercontent.com/124264994/227784279-78bf862b-365b-4d79-9bfa-6689f210395c.png">

[Sample of beardie-nm-connector.txt](https://github.com/Stillness-2/beardie/files/11071994/Sample.of.beardie-nm-connector.txt)

**Comment by bentoon00** [comment]
Process is making ~2 million unix sys calls a second

**Comment by sebastienbarre** [comment]
Can see that too on my Macbook Pro M1 Max :( Had to kill the process before it sets my knees on fire.

**Comment by Stillness-2** [comment]
@sebastienbarre #26

**Comment by sebastienbarre** [comment]
@Stillness-2 Thanks, but it just doesn't build for me. I opened the project in XCode, hit "Build", and it is failing in many different ways..

<img width="973" alt="image" src="https://github.com/Stillness-2/beardie/assets/329967/b221b1c9-46da-4ede-b677-525b57b11e29">

**Comment by Stillness-2** [comment]
@sebastienbarre Make a copy from `.devconfig.xcconfig.template` in the root of the repository, and replace the inside with the correct one

**Comment by sebastienbarre** [comment]
Thx. Though now it's only "No certificate matching 'Sign Identifier' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning."

Can this project be built locally without a certificate?

**Comment by sebastienbarre** [comment]
I'm afraid I don't know what that means.
